#Susanna
[Sus1]
"2" = '''2 And he took a wife named Susanna, the daughter of Hilkiah, a very
beautiful woman and one who feared the Lord.
'''
"3" = '''3 Her parents were righteous, and had taught their daughter according
to the law of Moses.
'''
"4" = '''4 Joakim was very rich, and had a spacious garden adjoining his
house; and the Jews used to come to him because he was the most honored
of them all.
'''
"5" = '''5
In that year two elders from the people were appointed as judges.
Concerning them the Lord had said: "Iniquity came forth from Babylon,
from elders who were judges, who were supposed to govern the people."
'''
"6" = '''6 These men were frequently at Joakim's house, and all who had suits
at law came to them.
'''
"7" = '''7
When the people departed at noon, Susanna would go into her husband's
garden to walk.
'''
"8" = '''8 The two elders used to see her every day, going in and walking
about, and they began to desire her.
'''
"9" = '''9 And they perverted their minds and turned away their eyes from
looking to Heaven or remembering righteous judgments.
'''
"10" = '''10 Both were overwhelmed with passion for her, but they did not tell
each other of their distress,
'''
"11" = '''11 for they were ashamed to disclose their lustful desire to possess
her.
'''
"12" = '''12 And they watched eagerly, day after day, to see her.
'''
"13" = '''13
They said to each other, "Let us go home, for it is mealtime."
'''
"14" = '''14 And when they went out, they parted from each other. But turning
back, they met again; and when each pressed the other for the reason,
they confessed their lust. And then together they arranged for a time
when they could find her alone.
'''
"15" = '''15
Once, while they were watching for an opportune day, she went in as
before with only two maids, and wished to bathe in the garden, for it
was very hot.
'''
"16" = '''16 And no one was there except the two elders, who had hid themselves
and were watching her.
'''
"17" = '''17 She said to her maids, "Bring me oil and ointments, and shut the
garden doors so that I may bathe."
'''
"18" = '''18 They did as she said, shut the garden doors, and went out by the
side doors to bring what they had been commanded; and they did not see
the elders, because they were hidden.
'''
"19" = '''19
When the maids had gone out, the two elders rose and ran to her, and
said:
'''
"20" = '''20 "Look, the garden doors are shut, no one sees us, and we are in
love with you; so give your consent, and lie with us.
'''
"21" = '''21 If you refuse, we will testify against you that a young man was
with you, and this was why you sent your maids away."
'''
"22" = '''22
Susanna sighed deeply, and said, "I am hemmed in on every side. For if
I do this thing, it is death for me; and if I do not, I shall not
escape your hands.
'''
"23" = '''23 I choose not to do it and to fall into your hands, rather than to
sin in the sight of the Lord."
'''
"24" = '''24
Then Susanna cried out with a loud voice, and the two elders shouted
against her.
'''
"25" = '''25 And one of them ran and opened the garden doors.
'''
"26" = '''26 When the household servants heard the shouting in the garden, they
rushed in at the side door to see what had happened to her.
'''
"27" = '''27 And when the elders told their tale, the servants were greatly
ashamed, for nothing like this had ever been said about Susanna.
'''
"28" = '''28
The next day, when the people gathered at the house of her husband
Joakim, the two elders came, full of their wicked plot to have Susanna
put to death.
'''
"29" = '''29 They said before the people, "Send for Susanna, the daughter of
Hilkiah, who is the wife of Joakim."
'''
"30" = '''30 So they sent for her. And she came, with her parents, her
children, and all her kindred.
'''
"31" = '''31
Now Susanna was a woman of great refinement, and beautiful in
appearance.
'''
"32" = '''32 As she was veiled, the wicked men ordered her to be unveiled, that
they might feed upon her beauty.
'''
"33" = '''33 But her family and friends and all who saw her wept.
'''
"34" = '''34
Then the two elders stood up in the midst of the people, and laid their
hands upon her head.
'''
"35" = '''35 And she, weeping, looked up toward heaven, for her heart trusted
in the Lord.
'''
"36" = '''36 The elders said, "As we were walking in the garden alone, this
woman came in with two maids, shut the garden doors, and dismissed the
maids.
'''
"37" = '''37 Then a young man, who had been hidden, came to her and lay with
her.
'''
"38" = '''38 We were in a corner of the garden, and when we saw this wickedness
we ran to them.
'''
"39" = '''39 We saw them embracing, but we could not hold the man, for he was
too strong for us, and he opened the doors and dashed out.
'''
"40" = '''40 So we seized this woman and asked her who the young man was, but
she would not tell us. These things we testify."
'''
"41" = '''41
The assembly believed them, because they were elders of the people and
judges; and they condemned her to death.
'''
"42" = '''42
Then Susanna cried out with a loud voice, and said, "O eternal God, who
dost discern what is secret, who art aware of all things before they
come to be,
'''
"43" = '''43 thou knowest that these men have borne false witness against me.
And now I am to die! Yet I have done none of the things that they have
wickedly invented against me!"
'''
"44" = '''44
The Lord heard her cry.
'''
"45" = '''45 And as she was being led away to be put to death, God aroused the
holy spirit of a young lad named Daniel;
'''
"46" = '''46 and he cried with a loud voice, "I am innocent of the blood of
this woman."
'''
"47" = '''47
All the people turned to him, and said, "What is this that you have
said?"
'''
"48" = '''48 Taking his stand in the midst of them, he said, "Are you such
fools, you sons of Israel? Have you condemned a daughter of Israel
without examination and without learning the facts?
'''
"49" = '''49 Return to the place of judgment. For these men have borne false
witness against her."
'''
"50" = '''50
Then all the people returned in haste. And the elders said to him,
"Come, sit among us and inform us, for God has given you that right."
'''
"51" = '''51 And Daniel said to them, "Separate them far from each other, and I
will examine them."
'''
"52" = '''52
When they were separated from each other, he summoned one of them and
said to him, "You old relic of wicked days, your sins have now come
home, which you have committed in the past,
'''
"53" = '''53 pronouncing unjust judgments, condemning the innocent and letting
the guilty go free, though the Lord said, `Do not put to death an
innocent and righteous person.'
'''
"54" = '''54 Now then, if you really saw her, tell me this: Under what tree did
you see them being intimate with each other?" He answered, "Under a
mastic tree."
'''
"55" = '''55 And Daniel said, "Very well! You have lied against your own head,
for the angel of God has received the sentence from God and will
immediately cut you in two."
'''
"56" = '''56
Then he put him aside, and commanded them to bring the other. And he
said to him, "You offspring of Canaan and not of Judah, beauty has
deceived you and lust has perverted your heart.
'''
"57" = '''57 This is how you both have been dealing with the daughters of
Israel, and they were intimate with you through fear; but a daughter of
Judah would not endure your wickedness.
'''
"58" = '''58 Now then, tell me: Under what tree did you catch them being
intimate with each other?" He answered, "Under an evergreen oak."
'''
"59" = '''59 And Daniel said to him, "Very well! You also have lied against
your own head, for the angel of God is waiting with his sword to saw
you in two, that he may destroy you both."
'''
"60" = '''60
Then all the assembly shouted loudly and blessed God, who saves those
who hope in him.
'''
"61" = '''61 And they rose against the two elders, for out of their own mouths
Daniel had convicted them of bearing false witness;
'''
"62" = '''62 and they did to them as they had wickedly planned to do to their
neighbor; acting in accordance with the law of Moses, they put them to
death. Thus innocent blood was saved that day.
'''
"63" = '''63
And Hilkiah and his wife praised God for their daughter Susanna, and so
did Joakim her husband and all her kindred, because nothing shameful
was found in her.
'''
"64" = '''64 And from that day onward Daniel had a great reputation among the
people.
'''
