#Prayer of Azariah
[PrAzar1]
"2" = '''2 Then Azariah stood and offered this prayer; in the midst of the
fire he opened his mouth and said:
'''
"3" = '''3 "Blessed art thou, O Lord, God of our fathers,
and worthy of praise;
and thy name is glorified for ever.
'''
"4" = '''4 For thou art just in all that thou hast done to us,
and all thy works are true and thy ways right,
and all thy judgments are truth.
'''
"5" = '''5 Thou hast executed true judgments in all that
thou hast brought upon us
and upon Jerusalem, the holy city of our fathers,
for in truth and justice thou hast brought
all this upon us because of our sins.
'''
"6" = '''6 For we have sinfully and lawlessly departed from thee,
and have sinned in all things and have not
obeyed thy commandments;
'''
"7" = '''7 we have not observed them or done them,
as thou hast commanded us that it might go well with us.
'''
"8" = '''8 So all that thou hast brought upon us,
and all that thou hast done to us,
thou hast done in true judgment.
'''
"9" = '''9 Thou hast given us into the hands of lawless
enemies, most hateful rebels,
and to an unjust king, the most wicked in all the world.
'''
"10" = '''10 And now we cannot open our mouths;
shame and disgrace have befallen thy servants and worshipers.
'''
"11" = '''11 For thy name's sake do not give us up utterly,
and do not break thy covenant,
'''
"12" = '''12 and do not withdraw thy mercy from us,
for the sake of Abraham thy beloved
and for the sake of Isaac thy servant
and Israel thy holy one,
'''
"13" = '''13 to whom thou didst promise
to make their descendants as many as the stars of heaven
and as the sand on the shore of the sea.
'''
"14" = '''14 For we, O Lord, have become fewer than any nation,
and are brought low this day in all the world
because of our sins.
'''
"15" = '''15 And at this time there is no prince, or prophet, or leader,
no burnt offering, or sacrifice, or oblation, or incense,
no place to make an offering before thee or to find mercy.
'''
"16" = '''16 Yet with a contrite heart and a humble spirit
may we be accepted,
as though it were with burnt offerings of rams and bulls,
and with tens of thousands of fat lambs;
'''
"17" = '''17 such may our sacrifice be in thy sight this day,
and may we wholly follow thee,
for there will be no shame for those who trust in thee.
'''
"18" = '''18 And now with all our heart we follow thee,
we fear thee and seek thy face.
'''
"19" = '''19 Do not put us to shame,
but deal with us in thy forbearance
and in thy abundant mercy.
'''
"20" = '''20 Deliver us in accordance with thy marvelous works,
and give glory to thy name, O Lord!
Let all who do harm to thy servants be put to shame;
'''
"21" = '''21 let them be disgraced and deprived of all power and dominion,
and let their strength be broken.
'''
"22" = '''22 Let them know that thou art the Lord, the only God,
glorious over the whole world."
'''
"23" = '''23
Now the king's servants who threw them in did not cease feeding the
furnace fires with naphtha, pitch, tow, and brush.
'''
"24" = '''24 And the flame streamed out above the furnace forty-nine cubits,
'''
"25" = '''25 and it broke through and burned those of the Chaldeans whom it
caught about the furnace.
'''
"26" = '''26 But the angel of the Lord came down into the furnace to be with
Azariah and his companions, and drove the fiery flame out of the
furnace,
'''
"27" = '''27 and made the midst of the furnace like a moist whistling wind, so
that the fire did not touch them at all or hurt or trouble them.
'''
"28" = '''28
Then the three, as with one mouth, praised and glorified and blessed
God in the furnace, saying:
'''
"29" = '''29 "Blessed art thou, O Lord, God of our fathers,
and to be praised and highly exalted for ever;
'''
"30" = '''30 And blessed is thy glorious, holy name
and to be highly praised and highly exalted for ever;
'''
"31" = '''31 Blessed art thou in the temple of thy holy glory
and to be extolled and highly glorified for ever.
'''
"32" = '''32 Blessed art thou, who sittest upon cherubim
and lookest upon the deeps,
and to be praised and highly exalted for ever.
'''
"33" = '''33 Blessed art thou upon the throne of thy kingdom
and to be extolled and highly exalted for ever.
'''
"34" = '''34 Blessed art thou in the firmament of heaven
and to be sung and glorified for ever.
'''
"35" = '''35 "Bless the Lord, all works of the Lord,
sing praise to him and highly exalt him for ever.
'''
"36" = '''36 Bless the Lord, you heavens,
sing praise to him and highly exalt him for ever.
'''
"37" = '''37 Bless the Lord, you angels of the Lord,
sing praise to him and highly exalt him for ever.
'''
"38" = '''38 Bless the Lord, all waters above the heaven,
sing praise to him and highly exalt him for ever.
'''
"39" = '''39 Bless the Lord, all powers,
sing praise to him and highly exalt him for ever.
'''
"40" = '''40 Bless the Lord, sun and moon,
sing praise to him and highly exalt him for ever.
'''
"41" = '''41 Bless the Lord, stars of heaven,
sing praise to him and highly exalt him for ever.
'''
"42" = '''42 Bless the Lord, all rain and dew,
sing praise to him and highly exalt him for ever.
'''
"43" = '''43 Bless the Lord, all winds,
sing praise to him and highly exalt him for ever.
'''
"44" = '''44 Bless the Lord, fire and heat,
sing praise to him and highly exalt him for ever.
'''
"45" = '''45 Bless the Lord, winter cold and summer heat,
sing praise to him and highly exalt him for ever.
'''
"46" = '''46 Bless the Lord, dews and snows,
sing praise to him and highly exalt him for ever.
'''
"47" = '''47 Bless the Lord, nights and days,
sing praise to him and highly exalt him for ever.
'''
"48" = '''48 Bless the Lord, light and darkness,
sing praise to him and highly exalt him for ever.
'''
"49" = '''49 Bless the Lord, ice and cold,
sing praise to him and highly exalt him for ever.
'''
"50" = '''50 Bless the Lord, frosts and snows,
sing praise to him and highly exalt him for ever.
'''
"51" = '''51 Bless the Lord, lightnings and clouds,
sing praise to him and highly exalt him for ever.
'''
"52" = '''52 Let the earth bless the Lord;
let it sing praise to him and highly exalt him for ever.
'''
"53" = '''53 Bless the Lord, mountains and hills,
sing praise to him and highly exalt him for ever.
'''
"54" = '''54 Bless the Lord, all things that grow on the earth,
sing praise to him and highly exalt him for ever.
'''
"55" = '''55 Bless the Lord, you springs,
sing praise to him and highly exalt him for ever.
'''
"56" = '''56 Bless the Lord, seas and rivers,
sing praise to him and highly exalt him for ever.
'''
"57" = '''57 Bless the Lord, you whales and all creatures
that move in the waters,
sing praise to him and highly exalt him for ever.
'''
"58" = '''58 Bless the Lord, all birds of the air,
sing praise to him and highly exalt him for ever.
'''
"59" = '''59 Bless the Lord, all beasts and cattle,
sing praise to him and highly exalt him for ever.
'''
"60" = '''60 Bless the Lord, you sons of men,
sing praise to him and highly exalt him for ever.
'''
"61" = '''61 Bless the Lord, O Israel,
sing praise to him and highly exalt him for ever.
'''
"62" = '''62 Bless the Lord, you priests of the Lord,
sing praise to him and highly exalt him for ever.
'''
"63" = '''63 Bless the Lord, you servants of the Lord,
sing praise to him and highly exalt him for ever.
'''
"64" = '''64 Bless the Lord, spirits and souls of the righteous,
sing praise to him and highly exalt him for ever.
'''
"65" = '''65 Bless the Lord, you who are holy and humble in heart,
sing praise to him and highly exalt him for ever.
'''
"66" = '''66 Bless the Lord, Hananiah, Azariah, and Mishael,
sing praise to him and highly exalt him for ever;
for he has rescued us from Hades and saved
us from the hand of death,
and delivered us from the midst of the burning fiery furnace;
from the midst of the fire he has delivered us.
'''
"67" = '''67 Give thanks to the Lord, for he is good,
for his mercy endures for ever.
'''
"68" = '''68 Bless him, all who worship the Lord, the God of gods,
sing praise to him and give thanks to him,
for his mercy endures for ever."
'''
