#Additions to the Book of Esther
[AddEsth10]

"1" = '''1
And Mordecai said, "These things have come from God.
'''
"2" = '''2 For I remember the dream that I had concerning these matters, and
none of them has failed to be fulfilled.
'''
"3" = '''3 The tiny spring which became a river, and there was light and the
sun and abundant water -- the river is Esther, whom the king married
and made queen.
'''
"4" = '''4 The two dragons are Haman and myself.
'''
"5" = '''5 The nations are those that gathered to destroy the name of the
Jews.
'''
"6" = '''6 And my nation, this is Israel, who cried out to God and were saved.
The Lord has saved his people; the Lord has delivered us from all these
evils; God has done great signs and wonders, which have not occurred
among the nations.
'''
"7" = '''7 For this purpose he made two lots, one for the people of God and
one for all the nations.
'''
"8" = '''8 And these two lots came to the hour and moment and day of decision
before God and among all the nations.
'''
"9" = '''9 And God remembered his people and vindicated his inheritance.
'''
"10" = '''10 So they will observe these days in the month of Adar, on the
fourteenth and fifteenth of that month, with an assembly and joy and
gladness before God, from generation to generation for ever among his
people Israel."
'''
[AddEsth11]

"1" = '''1
In the fourth year of the reign of Ptolemy and Cleopatra, Dositheus,
who said that he was a priest and a Levite, and Ptolemy his son brought
to Egypt the preceeding Letter of Purim, which they said was genuine
and had been translated by Lysimachus the son of Ptolemy, one of the
residents of Jerusalem.
'''
"2" = '''2 In the second year of the reign of Artaxerxes the Great, on the
first day of Nisan, Mordecai the son of Jair, son of Shimei, son of
Kish, of the tribe of Benjamin, had a dream.
'''
"3" = '''3 He was a Jew, dwelling in the city of Susa, a great man, serving in
the court of the king.
'''
"4" = '''4 He was one of the captives whom Nebuchadnezzar king of Babylon had
brought from Jerusalem with Jeconiah king of Judea. And this was his
dream:
'''
"5" = '''5 Behold, noise and confusion, thunders and earthquake, tumult upon
the earth!
'''
"6" = '''6 And behold, two great dragons came forward, both ready to fight,
and they roared terribly.
'''
"7" = '''7 And at their roaring every nation prepared for war, to fight
against the nation of the righteous.
'''
"8" = '''8 And behold, a day of darkness and gloom, tribulation and distress,
affliction and great tumult upon the earth!
'''
"9" = '''9 And the whole righteous nation was troubled; they feared the evils
that threatened them, and were ready to perish.
'''
"10" = '''10 Then they cried to God; and from their cry, as though from a tiny
spring, there came a great river, with abundant water;
'''
"11" = '''11 light came, and the sun rose, and the lowly were exalted and
consumed those held in honor.
'''
"12" = '''12
Mordecai saw in this dream what God had determined to do, and after he
awoke he had it on his mind and sought all day to understand it in
every detail.
'''
[AddEsth12]

"1" = '''1
Now Mordecai took his rest in the courtyard with Gabatha and Tharra,
the two eunuchs of the king who kept watch in the courtyard.
'''
"2" = '''2 He overheard their conversation and inquired into their purposes,
and learned that they were preparing to lay hands upon Artaxerxes the
king; and he informed the king concerning them.
'''
"3" = '''3 Then the king examined the two eunuchs, and when they confessed
they were led to execution.
'''
"4" = '''4 The king made a permanent record of these things, and Mordecai
wrote an account of them.
'''
"5" = '''5 And the king ordered Mordecai to serve in the court and rewarded
him for these things.
'''
"6" = '''6 But Haman, the son of Hammedatha, a Bougaean, was in great honor
with the king, and he sought to injure Mordecai and his people because
of the two eunuchs of the king.
'''
[AddEsth13]

"1" = '''1
This is a copy of the letter: "The Great King, Artaxerxes, to the
rulers of the hundred and twenty-seven provinces from India to Ethiopia
and to the governors under them, writes thus:
'''
"2" = '''2
"Having become ruler of many nations and master of the whole world, not
elated with presumption of authority but always acting reasonably and
with kindness, I have determined to settle the lives of my subjects in
lasting tranquillity and, in order to make my kingdom peaceable and
open to travel throughout all its extent, to re-establish the peace
which all men desire.
'''
"3" = '''3
"When I asked my counselors how this might be accomplished, Haman, who
excels among us in sound judgment, and is distinguished for his
unchanging good will and steadfast fidelity, and has attained the
second place in the kingdom,
'''
"4" = '''4 pointed out to us that among all the nations in the world there is
scattered a certain hostile people, who have laws contrary to those of
every nation and continually disregard the ordinances of the kings, so
that the unifying of the kingdom which we honorably intend cannot be
brought about.
'''
"5" = '''5 We understand that this people, and it alone, stands constantly in
opposition to all men, perversely following a strange manner of life
and laws, and is ill-disposed to our government, doing all the harm
they can so that our kingdom may not attain stability.
'''
"6" = '''6
"Therefore we have decreed that those indicated to you in the letters
of Haman, who is in charge of affairs and is our second father, shall
all, with their wives and children, be utterly destroyed by the sword
of their enemies, without pity or mercy, on the fourteenth day of the
twelfth month, Adar, of this present year,
'''
"7" = '''7 so that those who have long been and are now hostile may in one day
go down in violence to Hades, and leave our government completely
secure and untroubled hereafter."
'''
"8" = '''8
Then Mordecai prayed to the Lord, calling to remembrance all the works
of the Lord. He said:
'''
"9" = '''9
"O Lord, Lord, King who rulest over all things, for the universe is in
thy power and there is no one who can oppose thee if it is thy will to
save Israel.
'''
"10" = '''10 For thou hast made heaven and earth and every wonderful thing
under heaven,
'''
"11" = '''11 and thou art Lord of all, and there is no one who can resist thee,
who art the Lord.
'''
"12" = '''12 Thou knowest all things; thou knowest, O Lord, that it was not in
insolence or pride or for any love of glory that I did this, and
refused to bow down to this proud Haman.
'''
"13" = '''13 For I would have been willing to kiss the soles of his feet, to
save Israel!
'''
"14" = '''14 But I did this, that I might not set the glory of man above the
glory of God, and I will not bow down to any one but to thee, who art
my Lord; and I will not do these things in pride.
'''
"15" = '''15 And now, O Lord God and King, God of Abraham, spare thy people;
for the eyes of our foes are upon us to annihilate us, and they desire
to destroy the inheritance that has been thine from the beginning.
'''
"16" = '''16 Do not neglect thy portion, which thou didst redeem for thyself
out of the land of Egypt.
'''
"17" = '''17 Hear my prayer, and have mercy upon thy inheritance turn our
mourning into feasting, that we may live and sing praise to thy name, O
Lord; do not destroy the mouth of those who praise thee."
'''
"18" = '''18
And all Israel cried out mightily, for their death was before their
eyes.
'''
[AddEsth14]

"1" = '''1
And Esther the queen, seized with deathly anxiety, fled to the Lord;
'''
"2" = '''2 she took off her splendid apparel and put on the garments of
distress and mourning, and instead of costly perfumes she covered her
head with ashes and dung, and she utterly humbled her body, and every
part that she loved to adorn she covered with her tangled hair.
'''
"3" = '''3 And she prayed to the Lord God of Israel, and said:
Lord, thou only art our King; help me, who am alone and have no helper
but thee,
'''
"4" = '''4 for my danger is in my hand.
'''
"5" = '''5 Ever since I was born I have heard in the tribe of my family that
thou, O Lord, didst take Israel out of all the nations, and our fathers
from among all their ancestors, for an everlasting inheritance, and
that thou didst do for them all that thou didst promise.
'''
"6" = '''6 And now we have sinned before thee, and thou hast given us into the
hands of our enemies,
'''
"7" = '''7 because we glorified their gods. Thou art righteous, O Lord!
'''
"8" = '''8 And now they are not satisfied that we are in bitter slavery, but
they have covenanted with their idols
'''
"9" = '''9 to abolish what thy mouth has ordained and to destroy thy
inheritance, to stop the mouths of those who praise thee and to quench
thy altar and the glory of thy house,
'''
"10" = '''10 to open the mouths of the nations for the praise of vain idols,
and to magnify for ever a mortal king.
'''
"11" = '''11 O Lord, do not surrender thy scepter to what has no being; and do
not let them mock at our downfall; but turn their plan against
themselves, and make an example of the man who began this against us.
'''
"12" = '''12 Remember, O Lord; make thyself known in this time of our
affliction, and give me courage, O King of the gods and Master of all
dominion!
'''
"13" = '''13 Put eloquent speech in my mouth before the lion, and turn his
heart to hate the man who is fighting against us, so that there may be
an end of him and those who agree with him.
'''
"14" = '''14 But save us by thy hand, and help me, who am alone and have no
helper but thee, O Lord.
'''
"15" = '''15 Thou hast knowledge of all things; and thou knowest that I hate
the splendor of the wicked and abhor the bed of the uncircumcised and
of any alien.
'''
"16" = '''16 Thou knowest my necessity -- that I abhor the sign of my proud
position, which is upon my head on the days when I appear in public. I
abhor it like a menstruous rag, and I do not wear it on the days when I
am at leisure.
'''
"17" = '''17 And thy servant has not eaten at Haman's table, and I have not
honored the king's feast or drunk the wine of the libations.
'''
"18" = '''18 Thy servant has had no joy since the day that I was brought here
until now, except in thee, O Lord God of Abraham.
'''
"19" = '''19 O God, whose might is over all, hear the voice of the despairing,
and save us from the hands of evildoers. And save me from my fear!"
'''
[AddEsth15]

"1" = '''1
On the third day, when she ended her prayer, she took off the garments
in which she had worshiped, and arrayed herself in splendid attire.
'''
"2" = '''2 Then, majestically adorned, after invoking the aid of the
all-seeing God and Savior, she took her two maids with her,
'''
"3" = '''3 leaning daintily on one,
'''
"4" = '''4 while the other followed carrying her train.
'''
"5" = '''5 She was radiant with perfect beauty, and she looked happy, as if
beloved, but her heart was frozen with fear.
'''
"6" = '''6 When she had gone through all the doors, she stood before the king.
He was seated on his royal throne, clothed in the full array of his
majesty, all covered with gold and precious stones. And he was most
terrifying.
'''
"7" = '''7
Lifting his face, flushed with splendor, he looked at her in fierce
anger. And the queen faltered, and turned pale and faint, and collapsed
upon the head of the maid who went before her.
'''
"8" = '''8 Then God changed the spirit of the king to gentleness, and in alarm
he sprang from his throne and took her in his arms until she came to
herself. And he comforted her with soothing words, and said to her,
'''
"9" = '''9 "What is it, Esther? I am your brother. Take courage;
'''
"10" = '''10 you shall not die, for our law applies only to the people. Come
near."
'''
"11" = '''11
Then he raised the golden scepter and touched it to her neck;
'''
"12" = '''12 and he embraced her, and said, "Speak to me."
'''
"13" = '''13 And she said to him, "I saw you, my lord, like an angel of God and
my heart was shaken with fear at your glory.
'''
"14" = '''14 For you are wonderful, my lord, and your countenance is full of
grace."
'''
"15" = '''15 But as she was speaking, she fell fainting.
'''
"16" = '''16 And the king was agitated, and all his servants sought to comfort
her.
'''
[AddEsth16]

"1" = '''1
The following is a copy of this letter:
"The Great King, Artaxerxes, to the rulers of the provinces from India
to Ethiopia, one hundred and twenty-seven satrapies, and to those who
are loyal to our government, greeting.
'''
"2" = '''2
"The more often they are honored by the too great kindness of their
benefactors, the more proud do many men become.
'''
"3" = '''3 They not only seek to injure our subjects, but in their inability
to stand prosperity they even undertake to scheme against their own
benefactors.
'''
"4" = '''4 They not only take away thankfulness from among men, but, carried
away by the boasts of those who know nothing of goodness, they suppose
that they will escape the evil-hating justice of God, who always sees
everything.
'''
"5" = '''5 And often many of those who are set in places of authority have
been made in part responsible for the shedding of innocent blood, and
have been involved in irremediable calamities, by the persuasion of
friends who have been entrusted with the administration of public
affairs,
'''
"6" = '''6 when these men by the false trickery of their evil natures beguile
the sincere good will of their sovereigns.
'''
"7" = '''7
"What has been wickedly accomplished through the pestilent behavior of
those who exercise authority unworthily, can be seen not so much from
the more ancient records which we hand on as from investigation of
matters close at hand.
'''
"8" = '''8 For the future we will take care to render our kingdom quiet and
peaceable for all men,
'''
"9" = '''9 by changing our methods and always judging what comes before our
eyes with more equitable consideration.
'''
"10" = '''10 For Haman, the son of Hammedatha, a Macedonian (really an alien to
the Persian blood, and quite devoid of our kindliness), having become
our guest,
'''
"11" = '''11 so far enjoyed the good will that we have for every nation that he
was called our father and was continually bowed down to by all as the
person second to the royal throne.
'''
"12" = '''12 But, unable to restrain his arrogance, he undertook to deprive us
of our kingdom and our life,
'''
"13" = '''13 and with intricate craft and deceit asked for the destruction of
Mordecai, our savior and perpetual benefactor, and of Esther, the
blameless partner of our kingdom, together with their whole nation.
'''
"14" = '''14 He thought that in this way he would find us undefended and would
transfer the kingdom of the Persians to the Macedonians.
'''
"15" = '''15
"But we find that the Jews, who were consigned to annihilation by this
thrice accursed man, are not evildoers but are governed by most
righteous laws
'''
"16" = '''16 and are sons of the Most High, the most mighty living God, who has
directed the kingdom both for us and for our fathers in the most
excellent order.
'''
"17" = '''17
"You will therefore do well not to put in execution the letters sent by
Haman the son of Hammedatha,
'''
"18" = '''18 because the man himself who did these things has been hanged at
the gate of Susa, with all his household. For God, who rules over all
things, has speedily inflicted on him the punishment he deserved.
'''
"19" = '''19
"Therefore post a copy of this letter publicly in every place, and
permit the Jews to live under their own laws.
'''
"20" = '''20 And give them reinforcements, so that on the thirteenth day of the
twelfth month, Adar, on that very day they may defend themselves
against those who attack them at the time of their affliction.
'''
"21" = '''21 For God, who rules over all things, has made this day to be a joy
to his chosen people instead of a day of destruction for them.
'''
"22" = '''22
"Therefore you shall observe this with all good cheer as a notable day
among your commemorative festivals,
'''
"23" = '''23 so that both now and hereafter it may mean salvation for us and
the loyal Persians, but that for those who plot against us it may be a
reminder of destruction.
'''
"24" = '''24
"Every city and country, without exception, which does not act
accordingly, shall be destroyed in wrath with spear and fire. It shall
be made not only impassable for men, but also most hateful for all time
to beasts and birds."
'''
